const List<String> locationList = [
  'Swicc axis, Westend',
  'Westend 1&2 axis, Westend',
  'Sam P axis, Westend',
  'Ejanla axis, Westend',
  'Lambo axis, Westend',
  'Ajt 2 axis, Westend',
  'Alaga axis, Westend',
  'Amina Villa axis, Westend',
  'Mopelola axis, Westend',
  'Amao axis, Westend',
  'Police station, Westend',
  'Corner Stone, Westend',
  'Eplace , Westend',
  'Malete park, Malete',
  'Amina castle, Malete',
  'Baptist , Malete',
  'Tarmac axis , Malete',
  'Baba soja , Malete',
  'Maple, Malete',
  'Ecwa, Agric road',
  'Dara axis, Computer village',
  'Unique ajao axis, Computer village',
  'Liberation, Safari',
  'Gamos, Safari',
  'God\'s grace, Safari',
  'Agbeke ade, Safari',
  'chekas, Safari',
  'Olaronpe, Safari',
  '120 , Safari',
  'Millionaire, Safari',
  'Netherlands, Safari',
  'Banana island, Safari',
  'Sequence, Safari',
  'Felab, Safari',
  'Kings and queens , School gate Axis',
  'Dickalos, School gate Axis',
  'White house, School gate Axis',
  'Ojuolape, School gate Axis',
  'California, School gate Axis',
  'Great Villa, School gate Axis',
  'Dominion cottage, School gate Axis',
  'Taqwa  axis, School gate Axis',
];
